sudo: required
services:
  - docker

before_install:
  - docker build -t taulant/docker-react -f Dockerfile.dev .

script:
  - docker run taulant/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DocerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-372282608408"
    bucket_path: "docker-react"

    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: "$AWS_SECRET_KEY"